# -*- coding: utf-8 -*-
"""DBSCAN Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z12wt0GoyGbN4m5n_Y1oud0KY28KM6f0
"""

# Commented out IPython magic to ensure Python compatibility.
 from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons, make_circles
import matplotlib.pyplot as plt
# %matplotlib inline

#X,y=make_moons(n_samples=250,noise=0.05)

X,y=make_circles(n_samples=750,factor=0.3,noise=0.1)

X

plt.scatter(X[:,0],X[:,1])

##feature scaling(Standard Scaling)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_scaled=scaler.fit_transform(X)

X_scaled

dbcan=DBSCAN(eps=0.1)

dbcan.fit(X_scaled)

dbcan.labels_

plt.scatter(X[:,0],X[:,1],c=dbcan.labels_)

plt.scatter(X[:,0],X[:,1],c=y)

